CREATE DATABASE UAP1;
SHOW DATABASES;
USE UAP1;
CREATE TABLE UAPKAI(
NAMA VARCHAR(30) NOT NULL,
NIK VARCHAR(12) NOT NULL,
ALAMAT TEXT NOT NULL,
UMUR DOUBLE,
TGL_BERANGKAT DATE,
TUJUAN VARCHAR(20) NOT NULL,
JAM_KEBERANGKATAN VARCHAR(20) NOT NULL,
JENIS_KELAS VARCHAR(20) NOT NULL,
METODE_BAYAR VARCHAR(20) NOT NULL,
PRIMARY KEY(NIK));

